//
// FlowerItemDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FlowerItemDTO: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var category: Int
    public var title: String
    public var description: String?
    public var imageUrlSmall: String?
    public var imageUrlFull: String?

    public init(id: UUID, category: Int, title: String, description: String? = nil, imageUrlSmall: String? = nil, imageUrlFull: String? = nil) {
        self.id = id
        self.category = category
        self.title = title
        self.description = description
        self.imageUrlSmall = imageUrlSmall
        self.imageUrlFull = imageUrlFull
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case category
        case title
        case description
        case imageUrlSmall
        case imageUrlFull
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(category, forKey: .category)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(imageUrlSmall, forKey: .imageUrlSmall)
        try container.encodeIfPresent(imageUrlFull, forKey: .imageUrlFull)
    }
}

